<a href="https://colab.research.google.com/github/lorcan2440/Computing-Exercises/blob/main/Copy_of_07_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Make NumPy available:

In [1]:
import numpy as np

In [ ]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths (use a very long vector for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

#### (1) Add two vectors using built-in addition operator:

In [17]:
import random

x, y = np.random.rand(100000), np.random.rand(100000)
%time z = x + y
print(z)

CPU times: user 342 µs, sys: 47 µs, total: 389 µs
Wall time: 398 µs
[1.28649983 0.9762565  1.07655173 ... 0.7903444  0.62655216 1.09296046]


#### (2) Add two vectors using own implementation:

In [47]:
import random, numba

x, y = [random.random() for i in range(100000)], [random.random() for i in range(100000)]

print('Times using interpreted code:')
def add_vectors_interpreted(x: list, y: list):
  return [x[i] + y[i] for i in range(len(x))]
%time z = add_vectors_interpreted(x, y)

print('\nTimes using compiled code:')
@numba.jit
def add_vectors_compiled(x: list, y: list):
  return [x[i] + y[i] for i in range(len(x))]
%time z = add_vectors_compiled(x, y)

# Using JIT is slower??

Times using interpreted code:
CPU times: user 10.9 ms, sys: 0 ns, total: 10.9 ms
Wall time: 11 ms

Times using compiled code:
CPU times: user 536 ms, sys: 932 µs, total: 537 ms
Wall time: 538 ms


### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [25]:
!pip -q install numba 
import numba
import math

def compute_sine_native(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z

@numba.jit
def compute_sine_jit(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z
    
x = np.ones(10000000)
%time z = compute_sine_native(x)
compute_sine_jit(x)
%time z = compute_sine_jit(x)

CPU times: user 3.03 s, sys: 16 ms, total: 3.04 s
Wall time: 3.04 s
CPU times: user 182 ms, sys: 948 µs, total: 183 ms
Wall time: 183 ms


**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [99]:
def to_percentage_and_sort(scores):
  sorted_scores = scores.sort()
  return (scores / 60) * 100

def statistics(scores, exclude=False):
  if exclude:
    return {"min" : scores[1:-1].min(),
            "max" : scores[1:-1].max(),
            "mean": scores[1:-1].mean()}
  else:
    return {"min" : scores.min(),
            "max" : scores.max(),
            "mean": scores.mean()}

In [100]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert round(s0["min"] - 7.8, 10) == 0.0
assert round(s0["mean"] - 33.36, 10) == 0.0
assert round(s0["max"] - 58.0, 10) == 0.0

s1 = statistics(scores, True)
assert round(s1["min"] - 24.0, 10) == 0.0
assert round(s1["mean"] - 33.666666666666666667, 10) == 0.0
assert round(s1["max"] - 42.0, 10) == 0.0

## Exercise 07.3 (slicing)

For the two-dimensional array

In [103]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.



#### 1. Extract the third column as a 1D array

In [104]:
print(np.array([x[2] for x in A]))

[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [112]:
print(A[0:2])

[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [116]:
print(np.array([[x[-2], x[-1]] for x in [A[-2], A[-1]]]))

[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [117]:
print(sum([x[-1] for x in A]))

391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [118]:
print(np.transpose(A))

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [127]:
from scipy import optimize
global my_f

def my_f(x):
  return x**3 - 7*x**2 + 10*x - 11

def solve_bisection(my_f, x0, x1, tol, max_it):
  f = lambda x: my_f(x)
  i = 0
  a = x0
  b = x1
  f_mid = 1 + tol
  while i < max_it and abs(f_mid) > tol:
    x_mid = (a + b)/2
    f_0 = f(a)
    f_mid = f(x_mid)

    if f_0 * f_mid < 0:
      b = x_mid
    else:
      a = x_mid
    i += 1

  return x_mid, f_mid, i

def solve_scipy(my_f, x0, x1, tol, max_it):
  return optimize.bisect(my_f, x0, x1, xtol = tol, maxiter = max_it)

print('Bisection method times:')
%time x_bisect = solve_bisection(my_f, 4, 7, 1e-6, 10000)[0]
print(x_bisect)

print('\nScipy specialised function times:')
%time x_scipy = solve_scipy(my_f, 4, 7, 1e-6, 10000)
print(x_scipy)




Bisection method times:
CPU times: user 47 µs, sys: 0 ns, total: 47 µs
Wall time: 49.6 µs
5.55660542845726

Scipy specialised function times:
CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 38.4 µs
5.55660605430603
